# Generated by Django 5.0.1 on 2024-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_amount',
            field=models.IntegerField(default=0),
        ),
    ]
