# Generated by Django 5.0.2 on 2024-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_points_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="profile_images"),
        ),
    ]
