# Generated by Django 5.0.2 on 2024-02-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="Example_1.png", upload_to="profile_images"
            ),
        ),
    ]
