# Generated by Django 5.0.1 on 2024-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_avatarpart_is_default_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarpart',
            name='img_file',
            field=models.ImageField(upload_to='profile_images', verbose_name='Image file'),
        ),
    ]
