# Generated by Django 5.0.1 on 2024-03-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_avatarpart_remove_profile_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='colour',
            field=models.ForeignKey(limit_choices_to={'part_type': 'colour'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.avatarpart'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='eyes',
            field=models.ForeignKey(limit_choices_to={'part_type': 'eyes'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.avatarpart'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='mouth',
            field=models.ForeignKey(limit_choices_to={'part_type': 'mouth'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.avatarpart'),
        ),
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.avatarpart')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
