# Generated by Django 5.0.3 on 2024-03-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_avatarpart_remove_profile_avatar_avatar"),
    ]

    operations = [
        migrations.RenameModel("AvatarPart", "Item"),
        migrations.AddField(
            model_name="profile",
            name="coins_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="accessory",
            field=models.ForeignKey(
                limit_choices_to={"category": "accessory"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="users.item",
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="colour",
            field=models.ForeignKey(
                default="1",
                limit_choices_to={"category": "colour"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="users.item",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="avatar",
            name="eyes",
            field=models.ForeignKey(
                default="2",
                limit_choices_to={"category": "eyes"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="users.item",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="avatar",
            name="headwear",
            field=models.ForeignKey(
                limit_choices_to={"category": "headwear"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="users.item",
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="mouth",
            field=models.ForeignKey(
                default="3",
                limit_choices_to={"category": "mouth"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="users.item",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OwnedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.item"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
