# Generated by Django 5.0.1 on 2024-03-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_avatar_colour_alter_avatar_eyes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.avatarpart'),
        ),
        migrations.AlterField(
            model_name='owneditem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
