# Generated by Django 5.0.3 on 2024-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_item_profile_coins_amount_alter_avatar_accessory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="part_type",
            new_name="category",
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="is_default_img",
            field=models.BooleanField(
                default=False,
                verbose_name="Default (image is default selection for this item)",
            ),
        ),
    ]
