# Generated by Django 5.0.1 on 2024-03-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_owneditem_item_alter_owneditem_profile'),
    ]

    operations = [
        migrations.RenameModel(old_name='AvatarPart', new_name='Item'),
        migrations.AlterField(
            model_name='avatar',
            name='accessory',
            field=models.ForeignKey(limit_choices_to={'category': 'accessory'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.item'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='colour',
            field=models.ForeignKey(limit_choices_to={'category': 'colour'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.item'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='eyes',
            field=models.ForeignKey(limit_choices_to={'category': 'eyes'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.item'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='headwear',
            field=models.ForeignKey(limit_choices_to={'category': 'headwear'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.item'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='mouth',
            field=models.ForeignKey(limit_choices_to={'category': 'mouth'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.item'),
        ),
        migrations.AlterField(
            model_name='owneditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.item'),
        ),
    ]
