# Generated by Django 5.0.1 on 2024-03-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_item_alter_avatar_accessory_alter_avatar_colour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='part_type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_default_img',
            field=models.BooleanField(default=False, verbose_name='Default (image is default selection for this item)'),
        ),
    ]
