# Generated by Django 5.0.2 on 2024-02-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_qrcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="qr_image_base64",
            field=models.BinaryField(),
        ),
    ]
